name: CI

on: ['push', 'pull_request']

jobs:
  # Lint
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Use cache for npm"
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
  
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Use cache for npm"
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: "Use cache for Gatsby"
      uses: actions/cache@v1
      with:
        path: ./.cache
        key: ${{ runner.os }}-gatsby-dev-${{ hashFiles('**/package.json') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs:
    - lint
    - build
    steps:
    - uses: actions/checkout@v2
      if: github.ref == 'refs/heads/master'
    - name: "Use cache for npm"
      uses: actions/cache@v1
      if: github.ref == 'refs/heads/master'
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: "Use cache for Gatsby"
      uses: actions/cache@v1
      if: github.ref == 'refs/heads/master'
      with:
        path: ./.cache
        key: ${{ runner.os }}-gatsby-prod-${{ hashFiles('**/package.json') }}
    - name: "Clear source data"
      shell: bash
      run: rm -rf ./.cache/caches/@tsukuba-shinkan
    - uses: actions/setup-node@v1
      if: github.ref == 'refs/heads/master'
      with:
        node-version: 12.x
    - name: Install dependencies
      if: github.ref == 'refs/heads/master'
      run: npm ci
    - name: build
      if: github.ref == 'refs/heads/master'
      run: npm run build --prefix-paths
      env:
        SRC_FILE_ID: 1SDP5wlB7DtIa5pP1R7Idpw91RwbFUZuJczkW2kab9Vc 
        PREFIX_PATHS: /~shinkan-web
    - name: install lftp
      if: github.ref == 'refs/heads/master'
      run: sudo apt-get update && sudo apt-get install -y lftp
    - name: prepare .ssh dir
      if: github.ref == 'refs/heads/master'
      run: mkdir -p .ssh && chmod 700 .ssh
    - name: ssh key generate
      if: github.ref == 'refs/heads/master'
      run: echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: deploy with lftp
      if: github.ref == 'refs/heads/master'
      run: lftp -e "set net:max-retries 1; set sftp:connect-program \"ssh -a -x -p $SSH_PORT -i .ssh/id_rsa -o StrictHostKeyChecking=no\"; connect sftp://$SSH_USER:@$SSH_HOST; mirror -eR -x .git -x .ssh ./public $SSH_DIR; quit"
      env:
        SSH_PORT: 8022
        SSH_USER: shinkan-web
        SSH_HOST: www.stb.tsukuba.ac.jp
        SSH_DIR:  ~/public_html/
